### PR TITLE
Minor improvements for custom database annotation

### PR DESCRIPTION
**Pull request by lam-c**
Some bugs happened when using custom databases for annotation, so I simply modified codes to solve them. Changes are roughly about:

- Make Blast DB when executing `blastn` for annotating custom database, to resolve errors lacking index file for nucleotide db;
- Strip spaces in Shiny markdown for properly generating links to custom database reports.

There still exist bugs in custom database reports. Some of the report html file are empty when assigning multiple custom databases, while the annotation files (`.summary.txt`, `.gff`, both not empty) successfully completed. I'm not sure if this problem are caused by modification above.

Thank you soooo much for your patience, and this awesome tool!

### CODE REVIEW

**Comment by fmalmeida** [comment]
Hi @lam-c,
Thanks for using the pipelines and thanks more for helping improving it. Appreciate it 😄 

I will take a look at the changes later today to review the changes. I'll also let the example datasets running so we can make sure all works.

If all goes good, we can may have all merged whithin this week.

🚀 👍🏼

**Comment by fmalmeida** [comment]
Execution was successful for example dataset, now I just need to assess the changes on the shiny app.

**Comment by fmalmeida** [comment]
I am not sure about this comment:

> Some of the report html file are empty when assigning multiple custom

Is it possible for you to send the logs for the report executions? Also, have you tested if your changes fixed this?

😄

**Comment by fmalmeida** [comment]
I think I just ran into the error you mentioned. The error is basically that, even though the summary files are not empty, the tables in the reports are empty, right?

I will take a look on that.

**Comment by lam-c** [comment]
> I think I just ran into the error you mentioned. The error is basically that, even though the summary files are not empty, the tables in the reports are empty, right?
> 
> I will take a look on that.
> 
> Can you open an issue for that? I will link to this PR.

Exactly! I've opened an issue as you advised just now. The commond logs show that everything goes fine, I guess may be some bugs in `report_custom_blast.Rmd`.

Sorry for not replying sooner. MUCH lots of THANKS for prompt replies and active debugging!

**Comment by fmalmeida** [comment]
Hi @lam-c,
Since this PR you've opened seems to bring no problem to the PR but actually allowed you to run your analysis and get the html report files properly generated, I will merge this changes in the `develop` branch and close this PR. So you can use the pipeline from there.

Then, I will start to work on the issue you've opened which is not related to the workflow itself but to the shiny app which means I have to debug the shiny app code and this, should be tackled in another PR.

Many thanks for the contributions.

😄

**Pull request merged**
